//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNT2_2210900089_VuVietAnh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_MUC
    {
        public int MaDM { get; set; }
        public string TenDM { get; set; }
    }
}
